<?php return [
    '@meta' => [
        'language' => '日本語',
        'author' => 'Kohki SHIKATA',
        'date' => [
            'shortdays' => [
                '月',
                '火',
                '水',
                '木',
                '金',
                '土',
                '日'
            ],
            'longdays' => [
                '月曜日',
                '火曜日',
                '水曜日',
                '木曜日',
                '金曜日',
                '土曜日',
                '日曜日'
            ],
            'shortmonths' => [
                '1月',
                '2月',
                '3月',
                '4月',
                '5月',
                '6月',
                '7月',
                '8月',
                '9月',
                '10月',
                '11月',
                '12月'
            ],
            'longmonths' => [
                '1月',
                '2月',
                '3月',
                '4月',
                '5月',
                '6月',
                '7月',
                '8月',
                '9月',
                '10月',
                '11月',
                '12月'
            ]
        ]
    ],
    'Account' => 'アカウント',
    'Account removed' => 'アカウントは削除されました',
    'Account saved' => 'アカウントが保存sあれました',
    'Accounts' => 'アカウント',
    'Actions' => 'アクション',
    'Add Page' => 'ページを追加',
    'Add entry' => '記事を追加',
    'Add field' => 'フィールドを追加',
    'Add images' => '画像を追加',
    'Add item' => 'アイテムを追加',
    'Alternate Text' => 'Alternate Text',
    'Archive extracted!' => '保存データを展開しました',
    'Assets' => 'アセット',
    'Authenticate' => '認証',
    'Authenticate Please!' => '認証してください',
    'Author' => '執筆者',
    'Browse' => 'ブラウズ',
    'Buy a license' => 'ライセンスを購入',
    'Cancel' => 'キャンセル',
    'Close' => '閉じる',
    'Collection' => 'コレクション',
    'Collection removed' => 'コレクションは削除されました',
    'Collections' => 'コレクション',
    'Create Page' => '新しいページ概念の作成',
    'Create a collection' => '新しいコレクション概念の作成',
    'Create a form' => '新しいフォームの作成',
    'Create a page' => 'ページを作成',
    'Create a region' => 'リージョンの作成',
    'Create an entry' => '新しい記事の作成',
    'Create another page' => '別のページを作成',
    'Create config file' => '設定ファイルを作成',
    'Create one' => '1件追加',
    'Create one.' => '1件追加',
    'Custom config file does not exist' => 'カスタム設定ファイルが無いようです',
    'Custom config file is not writable' => 'カスタム設定ファイルに書き込み権限がありませんでした',
    'Dashboard' => '管理画面',
    'Default' => 'デフォルト',
    'Define collection fields' => 'コレクションのデータフィールドを設定',
    'Define region fields' => 'リージョンのデータフィールドを設定',
    'Delete' => '削除',
    'Description' => 'ディスクリプション',
    'Dimension' => 'Dimension',
    'Drag rows to reorder' => 'ドラッグで順序を入れ替えることができます',
    'Edit' => '編集',
    'Edit account' => 'アカウントを編集',
    'Email' => 'Eメール',
    'Entries' => 'エントリ',
    'Entries removed' => '複数のエントリが削除されました',
    'Entries reordered' => 'エントリの順序が変更されました',
    'Entry' => 'エントリ',
    'Entry removed' => 'エントリが削除されました',
    'Export entries' => 'エントリの書き出し',
    'Extracting archive failed!' => 'アーカイブのフィールドを展開しています',
    'Fields' => 'フィールド',
    'Fields definition is missing' => 'フィールド定義が見当たりません',
    'File deleted' => 'ファイルは削除されました',
    'File saved' => 'ファイルが保存されました',
    'File updated' => 'ファイルはアップデートされました',
    'File(s) deleted' => 'ファイルが削除されました',
    'File(s) failed to uploaded.' => 'ファイルのアップロードに失敗しました',
    'File(s) uploaded.' => 'ファイルがアップロードされました',
    'Filename' => 'ファイル名',
    'Files' => 'ファイル',
    'Files reordered' => 'ファイルの順序が変更されました',
    'Filetype not supported' => 'このファイルタイプは利用できません（未サポート）',
    'Filter by name...' => 'ファイル名で抽出',
    'Filter collections...' => 'コレクションの抽出',
    'Filter files...' => 'ファイルを抽出する',
    'Filter forms...' => 'フォームを抽出する',
    'Filter items...' => 'アイテムを抽出する',
    'Filter pages...' => 'ページを抽出する',
    'Filter regions...' => 'Filter regions...',
    'Finder' => 'ファインダー',
    'Folder reloaded' => 'フォルダを再読み込みしました',
    'Form' => 'フォーム',
    'Form removed' => 'フォームが削除されました',
    'Form submission failed.' => 'フォームからの入力ができませんでした',
    'Form submission was successful.' => 'フォームの入力を完了しました',
    'Forms' => 'フォーム',
    'Gallery is empty' => 'ギャラリーにデータがありません',
    'General' => '一般',
    'Generate from title' => 'タイトルから生成',
    'Group' => 'グループ',
    'Info' => '情報',
    'Item(s) deleted' => 'アイテムが削除されました',
    'Keywords' => 'キーワード',
    'Label' => 'ラベル',
    'Language' => '言語',
    'Last Modified' => '最終更新日時',
    'Leave the email field empty if you don\\\'t want to recieve any form data via email.' => 'Eメールフィールドが空欄の場合、データをEメールで受け取ることができません',
    'Leave the password field empty to keep your current password.' => 'パスワードフィールドが空欄の場合、現在のパスワードが使用されます',
    'Licensed to' => 'ライセンス付与：',
    'Load more..' => 'さらに読み込む',
    'Localize' => 'ローカライズ',
    'Localized field' => 'ローカライズフィールド',
    'Logout' => 'ログアウト',
    'Meta' => 'メタ情報',
    'Mime' => 'Mime',
    'Modified' => '変更',
    'Modules' => 'モジュール',
    'Name' => '名前',
    'New Password' => '新しいパスワード',
    'No Collections' => 'コレクションなし',
    'No collections' => 'コレクションなし',
    'No entries' => 'エントリーなし',
    'No entries found' => 'エントリーが見つかりませんでした',
    'No fields added yet' => 'フィールドがありません',
    'No fields defined' => 'フィールドが未定義です',
    'No file selected...' => 'ファイルが選択されていません',
    'No forms' => 'フォームなし',
    'No homepage.' => 'ホームページなし',
    'No items' => 'アイテムなし',
    'No pages.' => 'ページなし',
    'No regions' => 'リージョンなし',
    'Not saved yet' => 'まだ保存されていません',
    'Only alpha nummeric value is allowed' => '半角英数字で入力してください',
    'Options' => 'オプション',
    'Page removed' => 'ページは削除されました',
    'Page updated' => 'ページは更新されました',
    'Pages' => 'ページ',
    'Pages reordered' => 'ページの順序が変更されました',
    'Password' => 'パスワード',
    'Public link' => '公開リンク',
    'Region' => 'リージョン',
    'Region removed' => 'リージョンは削除されました',
    'Regions' => 'リージョン',
    'Remove image' => '画像は削除されました',
    'Reorder' => '順序の変更',
    'Required' => '必須',
    'Reset' => 'リセット',
    'Save' => '保存',
    'Save form data' => 'データから保存しました',
    'Saving failed.' => 'フィールドを保存しています',
    'Saving successful' => '保存が完了しました',
    'Search...' => '検索中...',
    'See all' => 'すべて表示',
    'Select image' => '画像の選択',
    'Set title' => 'タイトルの設定',
    'Settings' => '設定',
    'Settings updated' => '設定が変更されました',
    'Show' => '表示',
    'Show entries' => 'エントリの表示',
    'Show field on list view' => 'リストビューでフィールドを表示',
    'Show form' => 'フォームを表示',
    'Show in system menu' => 'システム項目で表示',
    'Site' => 'サイト',
    'Size' => 'サイズ',
    'Slug' => 'スラッグ',
    'Something went wrong.' => '不具合があるようです',
    'Sortable entries' => 'ソート可能なエントリ',
    'Status' => '状態',
    'Sub Pages' => '下層ページ',
    'System' => 'システム',
    'System Information' => 'システム情報',
    'System Settings' => 'システム設定',
    'System Update' => 'システムを更新',
    'Tags' => 'タグ',
    'Template' => 'テンプレート',
    'This is really experimental right now' => 'この機能は現在実験中です',
    'This page has no files' => 'このページにファイルは設定されていません',
    'This page has no files.' => 'このページにファイルは設定されていません',
    'This page has no sub-pages' => 'このページに下層ページは設定されていません',
    'This page has no sub-pages.' => 'このページに下層ページは設定されていません',
    'Title' => 'Title',
    'Unlicensed version. Enjoy your trial.' => 'ライセンス未承認。トライアルバージョンをお楽しみください',
    'Update' => 'アップデート',
    'Update order' => '順序の更新',
    'Upload files' => 'ファイルのアップロード',
    'Username' => 'ユーザー名',
    'Visibility' => '見えるかどうか',
    'You can\'t delete yourself' => 'あなたには削除できないようになっています',
    'info' => '情報',
    'label' => 'ラベル'
];
